<!DOCTYPE html>
<html lang="en">
<head>

<style>	

.affix {
      top: 0;
      width: 100%;
      z-index: 9999 !important;
  }

  .affix + .container-fluid {
      padding-top: 70px;
  }
	
	a.anchor {
    display: block;
    position: relative;
    top: -100px;
    visibility: hidden;
}

</style>


    
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>EMPOWER 2018: Assistive Technology Conference</title>
    <meta property="og:title" content="EMPOWER 2018: Assistive Technology Conference" />
    
    <meta property="og:url" content="http://assistech.iitd.ac.in/empower2018/" />
    <meta property="og:image" content="assets/images/og-image.jpg" />

    <!-- css -->
    <link rel="stylesheet" href="bower_components/bootstrap/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="bower_components/ionicons/css/ionicons.min.css">
    <link rel="stylesheet" href="assets/css/main.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <!-- Owl carousel -->
        <link rel="stylesheet" href="assets/css/owl.carousel.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<script>
	function closeOpenSession2b()
	{
		if($("#2a").is(":visible"))
			{
				$("#2a").toggle();
				$("#2a1").toggle();
				$("#2a2").toggle();
				$("#2a3").toggle();
				$("#2a4").toggle();
				$("#2a5").toggle();
				$("#2a6").toggle();
			}
		if($("#2c").is(":visible"))
			{
				$("#2c").toggle();
				$("#2c1").toggle();
				$("#2c2").toggle();
			}
		if($("#3a").is(":visible"))
			{
				$("#3a").toggle();
				$("#3a1").toggle();
				$("#3a2").toggle();
				$("#3a3").toggle();
				$("#3a4").toggle();
				$("#3a5").toggle();
				$("#3a6").toggle();
				$("#3a7").toggle();
			}
		if($("#3b").is(":visible"))
			{
				$("#3b").toggle();
				$("#3b1").toggle();
				$("#3b2").toggle();
			}
		if($("#3c").is(":visible"))
			{
				$("#3c").toggle();
				$("#3c1").toggle();
				$("#3c2").toggle();
			}
		if($("#6a").is(":visible"))
			{
				$("#6a").toggle();
				$("#6a1").toggle();
				$("#6a2").toggle();
				$("#6a3").toggle();
				$("#6a4").toggle();
				$("#6a5").toggle();
			}
		if($("#6b").is(":visible"))
			{
				$("#6b").toggle();
				$("#6b1").toggle();
				$("#6b2").toggle();
				$("#6b3").toggle();
			}
		if($("#6c").is(":visible"))
			{
				$("#6c").toggle();
				$("#6c1").toggle();
				$("#6c2").toggle();
				$("#6c3").toggle();
				$("#6c4").toggle();
			}
		if($("#7a").is(":visible"))
			{
				$("#7a").toggle();
				$("#7a1").toggle();
				$("#7a2").toggle();
				$("#7a3").toggle();
				$("#7a4").toggle();
				$("#7a5").toggle();
				$("#7a6").toggle();
			}
		if($("#7b").is(":visible"))
			{
				$("#7b").toggle();
				$("#7b1").toggle();
				$("#7b2").toggle();
				$("#7b3").toggle();
				$("#7b4").toggle();
				$("#7b5").toggle();
			}
		if($("#7c").is(":visible"))
			{
				$("#7c").toggle();
				$("#7c1").toggle();
				$("#7c2").toggle();
			}
		if($("#10a").is(":visible"))
			{
				$("#10a").toggle();
				$("#10a1").toggle();
				$("#10a2").toggle();
				$("#10a3").toggle();
			}
		if($("#10b").is(":visible"))
			{
				$("#10b").toggle();
				$("#10b1").toggle();
				$("#10b2").toggle();
				$("#10b3").toggle();
				$("#10b4").toggle();
				$("#10b5").toggle();
				$("#10b6").toggle();
			}
		if($("#10c").is(":visible"))
			{
				$("#10c").toggle();
				$("#10c1").toggle();
				$("#10c2").toggle();
				
			}
		if($("#11a").is(":visible"))
			{
				$("#11a").toggle();
				$("#11a1").toggle();
				$("#11a2").toggle();
				$("#11a3").toggle();
			}
		if($("#11b").is(":visible"))
			{
				$("#11b").toggle();
				$("#11b1").toggle();
				$("#11b2").toggle();
				$("#11b3").toggle();
				$("#11b4").toggle();
				$("#11b5").toggle();
				$("#11b6").toggle();
			}
		if($("#11c").is(":visible"))
			{
				$("#11c").toggle();
				$("#11c1").toggle();
				$("#11c2").toggle();
			}
		if($("#12a").is(":visible"))
			{
				$("#12a").toggle();
			}
	}
	
	function closeOpenSession2a()
	{
		if($("#2b").is(":visible"))
			{
				$("#2b").toggle();
				$("#2b1").toggle();
				$("#2b2").toggle();
			}
		if($("#2c").is(":visible"))
			{
				$("#2c").toggle();
				$("#2c1").toggle();
				$("#2c2").toggle();
			}
		if($("#3a").is(":visible"))
			{
				$("#3a").toggle();
				$("#3a1").toggle();
				$("#3a2").toggle();
				$("#3a3").toggle();
				$("#3a4").toggle();
				$("#3a5").toggle();
				$("#3a6").toggle();
				$("#3a7").toggle();
			}
		if($("#3b").is(":visible"))
			{
				$("#3b").toggle();
				$("#3b1").toggle();
				$("#3b2").toggle();
			}
		if($("#3c").is(":visible"))
			{
				$("#3c").toggle();
				$("#3c1").toggle();
				$("#3c2").toggle();
			}
		if($("#6a").is(":visible"))
			{
				$("#6a").toggle();
				$("#6a1").toggle();
				$("#6a2").toggle();
				$("#6a3").toggle();
				$("#6a4").toggle();
				$("#6a5").toggle();
			}
		if($("#6b").is(":visible"))
			{
				$("#6b").toggle();
				$("#6b1").toggle();
				$("#6b2").toggle();
				$("#6b3").toggle();
			}
		if($("#6c").is(":visible"))
			{
				$("#6c").toggle();
				$("#6c1").toggle();
				$("#6c2").toggle();
				$("#6c3").toggle();
				$("#6c4").toggle();
			}
		if($("#7a").is(":visible"))
			{
				$("#7a").toggle();
				$("#7a1").toggle();
				$("#7a2").toggle();
				$("#7a3").toggle();
				$("#7a4").toggle();
				$("#7a5").toggle();
				$("#7a6").toggle();
			}
		if($("#7b").is(":visible"))
			{
				$("#7b").toggle();
				$("#7b1").toggle();
				$("#7b2").toggle();
				$("#7b3").toggle();
				$("#7b4").toggle();
				$("#7b5").toggle();
			}
		if($("#7c").is(":visible"))
			{
				$("#7c").toggle();
				$("#7c1").toggle();
				$("#7c2").toggle();
			}
		if($("#10a").is(":visible"))
			{
				$("#10a").toggle();
				$("#10a1").toggle();
				$("#10a2").toggle();
				$("#10a3").toggle();
			}
		if($("#10b").is(":visible"))
			{
				$("#10b").toggle();
				$("#10b1").toggle();
				$("#10b2").toggle();
				$("#10b3").toggle();
				$("#10b4").toggle();
				$("#10b5").toggle();
				$("#10b6").toggle();
			}
		if($("#10c").is(":visible"))
			{
				$("#10c").toggle();
				$("#10c1").toggle();
				$("#10c2").toggle();
			}
		if($("#11a").is(":visible"))
			{
				$("#11a").toggle();
				$("#11a1").toggle();
				$("#11a2").toggle();
				$("#11a3").toggle();
			}
		if($("#11b").is(":visible"))
			{
				$("#11b").toggle();
				$("#11b1").toggle();
				$("#11b2").toggle();
				$("#11b3").toggle();
				$("#11b4").toggle();
				$("#11b5").toggle();
				$("#11b6").toggle();

			}
		if($("#11c").is(":visible"))
			{
				$("#11c").toggle();
				$("#11c1").toggle();
				$("#11c2").toggle();
			}
		if($("#12a").is(":visible"))
			{
				$("#12a").toggle();
			}
	}
	function closeOpenSession2c()
	{
		if($("#2b").is(":visible"))
			{
				$("#2b").toggle();
				$("#2b1").toggle();
				$("#2b2").toggle();
			}
		if($("#2a").is(":visible"))
			{
				$("#2a").toggle();
				$("#2a1").toggle();
				$("#2a2").toggle();
				$("#2a3").toggle();
				$("#2a4").toggle();
				$("#2a5").toggle();
				$("#2a6").toggle();
			}
		if($("#3a").is(":visible"))
			{
				$("#3a").toggle();
				$("#3a1").toggle();
				$("#3a2").toggle();
				$("#3a3").toggle();
				$("#3a4").toggle();
				$("#3a5").toggle();
				$("#3a6").toggle();
				$("#3a7").toggle();
			}
		if($("#3b").is(":visible"))
			{
				$("#3b").toggle();
				$("#3b1").toggle();
				$("#3b2").toggle();
			}
		if($("#3c").is(":visible"))
			{
				$("#3c").toggle();
				$("#3c1").toggle();
				$("#3c2").toggle();
			}
		if($("#6a").is(":visible"))
			{
				$("#6a").toggle();
				$("#6a1").toggle();
				$("#6a2").toggle();
				$("#6a3").toggle();
				$("#6a4").toggle();
				$("#6a5").toggle();
			}
		if($("#6b").is(":visible"))
			{
				$("#6b").toggle();
				$("#6b1").toggle();
				$("#6b2").toggle();
				$("#6b3").toggle();
			}
		if($("#6c").is(":visible"))
			{
				$("#6c").toggle();
				$("#6c1").toggle();
				$("#6c2").toggle();
				$("#6c3").toggle();
				$("#6c4").toggle();
			}
		if($("#7a").is(":visible"))
			{
				$("#7a").toggle();
				$("#7a1").toggle();
				$("#7a2").toggle();
				$("#7a3").toggle();
				$("#7a4").toggle();
				$("#7a5").toggle();
				$("#7a6").toggle();
			}
		if($("#7b").is(":visible"))
			{
				$("#7b").toggle();
				$("#7b1").toggle();
				$("#7b2").toggle();
				$("#7b3").toggle();
				$("#7b4").toggle();
				$("#7b5").toggle();
			}
		if($("#7c").is(":visible"))
			{
				$("#7c").toggle();
				$("#7c1").toggle();
				$("#7c2").toggle();
			}
		if($("#10a").is(":visible"))
			{
				$("#10a").toggle();
				$("#10a1").toggle();
				$("#10a2").toggle();
				$("#10a3").toggle();
			}
		if($("#10b").is(":visible"))
			{
				$("#10b").toggle();
				$("#10b1").toggle();
				$("#10b2").toggle();
				$("#10b3").toggle();
				$("#10b4").toggle();
				$("#10b5").toggle();
				$("#10b6").toggle();
			}
		if($("#10c").is(":visible"))
			{
				$("#10c").toggle();
				$("#10c1").toggle();
				$("#10c2").toggle();
			}
		if($("#11a").is(":visible"))
			{
				$("#11a").toggle();
				$("#11a1").toggle();
				$("#11a2").toggle();
				$("#11a3").toggle();
			}
		if($("#11b").is(":visible"))
			{
				$("#11b").toggle();
				$("#11b1").toggle();
				$("#11b2").toggle();
				$("#11b3").toggle();
				$("#11b4").toggle();
				$("#11b5").toggle();
				$("#11b6").toggle();

			}
		if($("#11c").is(":visible"))
			{
				$("#11c").toggle();
				$("#11c1").toggle();
				$("#11c2").toggle();
			}
		if($("#12a").is(":visible"))
			{
				$("#12a").toggle();
			}
	}
	function closeOpenSession3a()
	{
		if($("#2a").is(":visible"))
			{
				$("#2a").toggle();
				$("#2a1").toggle();
				$("#2a2").toggle();
				$("#2a3").toggle();
				$("#2a4").toggle();
				$("#2a5").toggle();
				$("#2a6").toggle();
			}
		if($("#2b").is(":visible"))
			{
				$("#2b").toggle();
				$("#2b1").toggle();
				$("#2b2").toggle();
			}
		if($("#2c").is(":visible"))
			{
				$("#2c").toggle();
				$("#2c1").toggle();
				$("#2c2").toggle();
			}
		if($("#3b").is(":visible"))
			{
				$("#3b").toggle();
				$("#3b1").toggle();
				$("#3b2").toggle();
			}
		if($("#3c").is(":visible"))
			{
				$("#3c").toggle();
				$("#3c1").toggle();
				$("#3c2").toggle();
			}
		if($("#6a").is(":visible"))
			{
				$("#6a").toggle();
				$("#6a1").toggle();
				$("#6a2").toggle();
				$("#6a3").toggle();
				$("#6a4").toggle();
				$("#6a5").toggle();
			}
		if($("#6b").is(":visible"))
			{
				$("#6b").toggle();
				$("#6b1").toggle();
				$("#6b2").toggle();
				$("#6b3").toggle();
			}
		if($("#6c").is(":visible"))
			{
				$("#6c").toggle();
				$("#6c1").toggle();
				$("#6c2").toggle();
				$("#6c3").toggle();
				$("#6c4").toggle();
			}
		if($("#7a").is(":visible"))
			{
				$("#7a").toggle();
				$("#7a1").toggle();
				$("#7a2").toggle();
				$("#7a3").toggle();
				$("#7a4").toggle();
				$("#7a5").toggle();
				$("#7a6").toggle();
			}
		if($("#7b").is(":visible"))
			{
				$("#7b").toggle();
				$("#7b1").toggle();
				$("#7b2").toggle();
				$("#7b3").toggle();
				$("#7b4").toggle();
				$("#7b5").toggle();
			}
		if($("#7c").is(":visible"))
			{
				$("#7c").toggle();
				$("#7c1").toggle();
				$("#7c2").toggle();
			}
		if($("#10a").is(":visible"))
			{
				$("#10a").toggle();
				$("#10a1").toggle();
				$("#10a2").toggle();
				$("#10a3").toggle();
			}
		if($("#10b").is(":visible"))
			{
				$("#10b").toggle();
				$("#10b1").toggle();
				$("#10b2").toggle();
				$("#10b3").toggle();
				$("#10b4").toggle();
				$("#10b5").toggle();
				$("#10b6").toggle();
			}
		if($("#10c").is(":visible"))
			{
				$("#10c").toggle();
				$("#10c1").toggle();
				$("#10c2").toggle();
			}
		if($("#11a").is(":visible"))
			{
				$("#11a").toggle();
				$("#11a1").toggle();
				$("#11a2").toggle();
				$("#11a3").toggle();
			}
		if($("#11b").is(":visible"))
			{
				$("#11b").toggle();
				$("#11b1").toggle();
				$("#11b2").toggle();
				$("#11b3").toggle();
				$("#11b4").toggle();
				$("#11b5").toggle();
				$("#11b6").toggle();

			}
		if($("#11c").is(":visible"))
			{
				$("#11c").toggle();
				$("#11c1").toggle();
				$("#11c2").toggle();
			}
		if($("#12a").is(":visible"))
			{
				$("#12a").toggle();
			}
	}
	function closeOpenSession3b()
	{
		if($("#2a").is(":visible"))
			{
				$("#2a").toggle();
				$("#2a1").toggle();
				$("#2a2").toggle();
				$("#2a3").toggle();
				$("#2a4").toggle();
				$("#2a5").toggle();
				$("#2a6").toggle();
			}
		if($("#2b").is(":visible"))
			{
				$("#2b").toggle();
				$("#2b1").toggle();
				$("#2b2").toggle();
			}
		if($("#2c").is(":visible"))
			{
				$("#2c").toggle();
				$("#2c1").toggle();
				$("#2c2").toggle();
			}
		if($("#3a").is(":visible"))
			{
				$("#3a").toggle();
				$("#3a1").toggle();
				$("#3a2").toggle();
				$("#3a3").toggle();
				$("#3a4").toggle();
				$("#3a5").toggle();
				$("#3a6").toggle();
				$("#3a7").toggle();
			}
		if($("#3c").is(":visible"))
			{
				$("#3c").toggle();
				$("#3c1").toggle();
				$("#3c2").toggle();
			}
		if($("#6a").is(":visible"))
			{
				$("#6a").toggle();
				$("#6a1").toggle();
				$("#6a2").toggle();
				$("#6a3").toggle();
				$("#6a4").toggle();
				$("#6a5").toggle();
			}
		if($("#6b").is(":visible"))
			{
				$("#6b").toggle();
				$("#6b1").toggle();
				$("#6b2").toggle();
				$("#6b3").toggle();
			}
		if($("#6c").is(":visible"))
			{
				$("#6c").toggle();
				$("#6c1").toggle();
				$("#6c2").toggle();
				$("#6c3").toggle();
				$("#6c4").toggle();
			}
		if($("#7a").is(":visible"))
			{
				$("#7a").toggle();
				$("#7a1").toggle();
				$("#7a2").toggle();
				$("#7a3").toggle();
				$("#7a4").toggle();
				$("#7a5").toggle();
				$("#7a6").toggle();
			}
		if($("#7b").is(":visible"))
			{
				$("#7b").toggle();
				$("#7b1").toggle();
				$("#7b2").toggle();
				$("#7b3").toggle();
				$("#7b4").toggle();
				$("#7b5").toggle();
			}
		if($("#7c").is(":visible"))
			{
				$("#7c").toggle();
				$("#7c1").toggle();
				$("#7c2").toggle();
			}
		if($("#10a").is(":visible"))
			{
				$("#10a").toggle();
				$("#10a1").toggle();
				$("#10a2").toggle();
				$("#10a3").toggle();
			}
		if($("#10b").is(":visible"))
			{
				$("#10b").toggle();
				$("#10b1").toggle();
				$("#10b2").toggle();
				$("#10b3").toggle();
				$("#10b4").toggle();
				$("#10b5").toggle();
				$("#10b6").toggle();
			}
		if($("#10c").is(":visible"))
			{
				$("#10c").toggle();
				$("#10c1").toggle();
				$("#10c2").toggle();
			}
		if($("#11a").is(":visible"))
			{
				$("#11a").toggle();
				$("#11a1").toggle();
				$("#11a2").toggle();
				$("#11a3").toggle();
			}
		if($("#11b").is(":visible"))
			{
				$("#11b").toggle();
				$("#11b1").toggle();
				$("#11b2").toggle();
				$("#11b3").toggle();
				$("#11b4").toggle();
				$("#11b5").toggle();
				$("#11b6").toggle();

			}
		if($("#11c").is(":visible"))
			{
				$("#11c").toggle();
				$("#11c1").toggle();
				$("#11c2").toggle();
			}
		if($("#12a").is(":visible"))
			{
				$("#12a").toggle();
			}
	}
	function closeOpenSession3c()
	{
		if($("#2a").is(":visible"))
			{
				$("#2a").toggle();
				$("#2a1").toggle();
				$("#2a2").toggle();
				$("#2a3").toggle();
				$("#2a4").toggle();
				$("#2a5").toggle();
				$("#2a6").toggle();
			}
		if($("#2b").is(":visible"))
			{
				$("#2b").toggle();
				$("#2b1").toggle();
				$("#2b2").toggle();
			}
		if($("#2c").is(":visible"))
			{
				$("#2c").toggle();
				$("#2c1").toggle();
				$("#2c2").toggle();
			}
		if($("#3a").is(":visible"))
			{
				$("#3a").toggle();
				$("#3a1").toggle();
				$("#3a2").toggle();
				$("#3a3").toggle();
				$("#3a4").toggle();
				$("#3a5").toggle();
				$("#3a6").toggle();
				$("#3a7").toggle();
			}
		if($("#3b").is(":visible"))
			{
				$("#3b").toggle();
				$("#3b1").toggle();
				$("#3b2").toggle();
			}
		if($("#6a").is(":visible"))
			{
				$("#6a").toggle();
				$("#6a1").toggle();
				$("#6a2").toggle();
				$("#6a3").toggle();
				$("#6a4").toggle();
				$("#6a5").toggle();
			}
		if($("#6b").is(":visible"))
			{
				$("#6b").toggle();
				$("#6b1").toggle();
				$("#6b2").toggle();
				$("#6b3").toggle();
			}
		if($("#6c").is(":visible"))
			{
				$("#6c").toggle();
				$("#6c1").toggle();
				$("#6c2").toggle();
				$("#6c3").toggle();
				$("#6c4").toggle();
			}
		if($("#7a").is(":visible"))
			{
				$("#7a").toggle();
				$("#7a1").toggle();
				$("#7a2").toggle();
				$("#7a3").toggle();
				$("#7a4").toggle();
				$("#7a5").toggle();
				$("#7a6").toggle();
			}
		if($("#7b").is(":visible"))
			{
				$("#7b").toggle();
				$("#7b1").toggle();
				$("#7b2").toggle();
				$("#7b3").toggle();
				$("#7b4").toggle();
				$("#7b5").toggle();
			}
		if($("#7c").is(":visible"))
			{
				$("#7c").toggle();
				$("#7c1").toggle();
				$("#7c2").toggle();
			}
		if($("#10a").is(":visible"))
			{
				$("#10a").toggle();
				$("#10a1").toggle();
				$("#10a2").toggle();
				$("#10a3").toggle();
			}
		if($("#10b").is(":visible"))
			{
				$("#10b").toggle();
				$("#10b1").toggle();
				$("#10b2").toggle();
				$("#10b3").toggle();
				$("#10b4").toggle();
				$("#10b5").toggle();
				$("#10b6").toggle();
			}
		if($("#10c").is(":visible"))
			{
				$("#10c").toggle();
				$("#10c1").toggle();
				$("#10c2").toggle();
			}
		if($("#11a").is(":visible"))
			{
				$("#11a").toggle();
				$("#11a1").toggle();
				$("#11a2").toggle();
				$("#11a3").toggle();
			}
		if($("#11b").is(":visible"))
			{
				$("#11b").toggle();
				$("#11b1").toggle();
				$("#11b2").toggle();
				$("#11b3").toggle();
				$("#11b4").toggle();
				$("#11b5").toggle();
				$("#11b6").toggle();

			}
		if($("#11c").is(":visible"))
			{
				$("#11c").toggle();
				$("#11c1").toggle();
				$("#11c2").toggle();
			}
		if($("#12a").is(":visible"))
			{
				$("#12a").toggle();
			}
	}
	function closeOpenSession6a()
	{
		if($("#2a").is(":visible"))
			{
				$("#2a").toggle();
				$("#2a1").toggle();
				$("#2a2").toggle();
				$("#2a3").toggle();
				$("#2a4").toggle();
				$("#2a5").toggle();
				$("#2a6").toggle();
			}
		if($("#2b").is(":visible"))
			{
				$("#2b").toggle();
				$("#2b1").toggle();
				$("#2b2").toggle();
			}
		if($("#2c").is(":visible"))
			{
				$("#2c").toggle();
				$("#2c1").toggle();
				$("#2c2").toggle();
			}
		if($("#3a").is(":visible"))
			{
				$("#3a").toggle();
				$("#3a1").toggle();
				$("#3a2").toggle();
				$("#3a3").toggle();
				$("#3a4").toggle();
				$("#3a5").toggle();
				$("#3a6").toggle();
				$("#3a7").toggle();
			}
		if($("#3b").is(":visible"))
			{
				$("#3b").toggle();
				$("#3b1").toggle();
				$("#3b2").toggle();
			}
		if($("#3c").is(":visible"))
			{
				$("#3c").toggle();
				$("#3c1").toggle();
				$("#3c2").toggle();
			}
		if($("#6b").is(":visible"))
			{
				$("#6b").toggle();
				$("#6b1").toggle();
				$("#6b2").toggle();
				$("#6b3").toggle();
			}
		if($("#6c").is(":visible"))
			{
				$("#6c").toggle();
				$("#6c1").toggle();
				$("#6c2").toggle();
				$("#6c3").toggle();
				$("#6c4").toggle();
			}
		if($("#7a").is(":visible"))
			{
				$("#7a").toggle();
				$("#7a1").toggle();
				$("#7a2").toggle();
				$("#7a3").toggle();
				$("#7a4").toggle();
				$("#7a5").toggle();
				$("#7a6").toggle();
			}
		if($("#7b").is(":visible"))
			{
				$("#7b").toggle();
				$("#7b1").toggle();
				$("#7b2").toggle();
				$("#7b3").toggle();
				$("#7b4").toggle();
				$("#7b5").toggle();
			}
		if($("#7c").is(":visible"))
			{
				$("#7c").toggle();
				$("#7c1").toggle();
				$("#7c2").toggle();
			}
		if($("#10a").is(":visible"))
			{
				$("#10a").toggle();
				$("#10a1").toggle();
				$("#10a2").toggle();
				$("#10a3").toggle();
			}
		if($("#10b").is(":visible"))
			{
				$("#10b").toggle();
				$("#10b1").toggle();
				$("#10b2").toggle();
				$("#10b3").toggle();
				$("#10b4").toggle();
				$("#10b5").toggle();
				$("#10b6").toggle();
			}
		if($("#10c").is(":visible"))
			{
				$("#10c").toggle();
				$("#10c1").toggle();
				$("#10c2").toggle();
			}
		if($("#11a").is(":visible"))
			{
				$("#11a").toggle();
				$("#11a1").toggle();
				$("#11a2").toggle();
				$("#11a3").toggle();
			}
		if($("#11b").is(":visible"))
			{
				$("#11b").toggle();
				$("#11b1").toggle();
				$("#11b2").toggle();
				$("#11b3").toggle();
				$("#11b4").toggle();
				$("#11b5").toggle();
				$("#11b6").toggle();

			}
		if($("#11c").is(":visible"))
			{
				$("#11c").toggle();
				$("#11c1").toggle();
				$("#11c2").toggle();
			}
		if($("#12a").is(":visible"))
			{
				$("#12a").toggle();
			}
	}
	function closeOpenSession6b()
	{
		if($("#2a").is(":visible"))
			{
				$("#2a").toggle();
				$("#2a1").toggle();
				$("#2a2").toggle();
				$("#2a3").toggle();
				$("#2a4").toggle();
				$("#2a5").toggle();
				$("#2a6").toggle();
			}
		if($("#2b").is(":visible"))
			{
				$("#2b").toggle();
				$("#2b1").toggle();
				$("#2b2").toggle();
			}
		if($("#2c").is(":visible"))
			{
				$("#2c").toggle();
				$("#2c1").toggle();
				$("#2c2").toggle();
			}
		if($("#3a").is(":visible"))
			{
				$("#3a").toggle();
				$("#3a1").toggle();
				$("#3a2").toggle();
				$("#3a3").toggle();
				$("#3a4").toggle();
				$("#3a5").toggle();
				$("#3a6").toggle();
				$("#3a7").toggle();
			}
		if($("#3b").is(":visible"))
			{
				$("#3b").toggle();
				$("#3b1").toggle();
				$("#3b2").toggle();
			}
		if($("#3c").is(":visible"))
			{
				$("#3c").toggle();
				$("#3c1").toggle();
				$("#3c2").toggle();
			}
		if($("#6a").is(":visible"))
			{
				$("#6a").toggle();
				$("#6a1").toggle();
				$("#6a2").toggle();
				$("#6a3").toggle();
				$("#6a4").toggle();
				$("#6a5").toggle();
			}
		if($("#6c").is(":visible"))
			{
				$("#6c").toggle();
				$("#6c1").toggle();
				$("#6c2").toggle();
				$("#6c3").toggle();
				$("#6c4").toggle();
			}
		if($("#7a").is(":visible"))
			{
				$("#7a").toggle();
				$("#7a1").toggle();
				$("#7a2").toggle();
				$("#7a3").toggle();
				$("#7a4").toggle();
				$("#7a5").toggle();
				$("#7a6").toggle();
			}
		if($("#7b").is(":visible"))
			{
				$("#7b").toggle();
				$("#7b1").toggle();
				$("#7b2").toggle();
				$("#7b3").toggle();
				$("#7b4").toggle();
				$("#7b5").toggle();
			}
		if($("#7c").is(":visible"))
			{
				$("#7c").toggle();
				$("#7c1").toggle();
				$("#7c2").toggle();
			}
		if($("#10a").is(":visible"))
			{
				$("#10a").toggle();
				$("#10a1").toggle();
				$("#10a2").toggle();
				$("#10a3").toggle();
			}
		if($("#10b").is(":visible"))
			{
				$("#10b").toggle();
				$("#10b1").toggle();
				$("#10b2").toggle();
				$("#10b3").toggle();
				$("#10b4").toggle();
				$("#10b5").toggle();
				$("#10b6").toggle();
			}
		if($("#10c").is(":visible"))
			{
				$("#10c").toggle();
				$("#10c1").toggle();
				$("#10c2").toggle();
			}
		if($("#11a").is(":visible"))
			{
				$("#11a").toggle();
				$("#11a1").toggle();
				$("#11a2").toggle();
				$("#11a3").toggle();
			}
		if($("#11b").is(":visible"))
			{
				$("#11b").toggle();
				$("#11b1").toggle();
				$("#11b2").toggle();
				$("#11b3").toggle();
				$("#11b4").toggle();
				$("#11b5").toggle();
				$("#11b6").toggle();

			}
		if($("#11c").is(":visible"))
			{
				$("#11c").toggle();
				$("#11c1").toggle();
				$("#11c2").toggle();
			}
		if($("#12a").is(":visible"))
			{
				$("#12a").toggle();
			}
	}
	function closeOpenSession6c()
	{
		if($("#2a").is(":visible"))
			{
				$("#2a").toggle();
				$("#2a1").toggle();
				$("#2a2").toggle();
				$("#2a3").toggle();
				$("#2a4").toggle();
				$("#2a5").toggle();
				$("#2a6").toggle();
			}
		if($("#2b").is(":visible"))
			{
				$("#2b").toggle();
				$("#2b1").toggle();
				$("#2b2").toggle();
			}
		if($("#2c").is(":visible"))
			{
				$("#2c").toggle();
				$("#2c1").toggle();
				$("#2c2").toggle();
			}
		if($("#3a").is(":visible"))
			{
				$("#3a").toggle();
				$("#3a1").toggle();
				$("#3a2").toggle();
				$("#3a3").toggle();
				$("#3a4").toggle();
				$("#3a5").toggle();
				$("#3a6").toggle();
				$("#3a7").toggle();
			}
		if($("#3b").is(":visible"))
			{
				$("#3b").toggle();
				$("#3b1").toggle();
				$("#3b2").toggle();
			}
		if($("#3c").is(":visible"))
			{
				$("#3c").toggle();
				$("#3c1").toggle();
				$("#3c2").toggle();
			}
		if($("#6a").is(":visible"))
			{
				$("#6a").toggle();
				$("#6a1").toggle();
				$("#6a2").toggle();
				$("#6a3").toggle();
				$("#6a4").toggle();
				$("#6a5").toggle();
			}
		if($("#6b").is(":visible"))
			{
				$("#6b").toggle();
				$("#6b1").toggle();
				$("#6b2").toggle();
				$("#6b3").toggle();
			}
		if($("#7a").is(":visible"))
			{
				$("#7a").toggle();
				$("#7a1").toggle();
				$("#7a2").toggle();
				$("#7a3").toggle();
				$("#7a4").toggle();
				$("#7a5").toggle();
				$("#7a6").toggle();
			}
		if($("#7b").is(":visible"))
			{
				$("#7b").toggle();
				$("#7b1").toggle();
				$("#7b2").toggle();
				$("#7b3").toggle();
				$("#7b4").toggle();
				$("#7b5").toggle();
			}
		if($("#7c").is(":visible"))
			{
				$("#7c").toggle();
				$("#7c1").toggle();
				$("#7c2").toggle();
			}
		if($("#10a").is(":visible"))
			{
				$("#10a").toggle();
				$("#10a1").toggle();
				$("#10a2").toggle();
				$("#10a3").toggle();
			}
		if($("#10b").is(":visible"))
			{
				$("#10b").toggle();
				$("#10b1").toggle();
				$("#10b2").toggle();
				$("#10b3").toggle();
				$("#10b4").toggle();
				$("#10b5").toggle();
				$("#10b6").toggle();
			}
		if($("#10c").is(":visible"))
			{
				$("#10c").toggle();
				$("#10c1").toggle();
				$("#10c2").toggle();
			}
		if($("#11a").is(":visible"))
			{
				$("#11a").toggle();
				$("#11a1").toggle();
				$("#11a2").toggle();
				$("#11a3").toggle();
			}
		if($("#11b").is(":visible"))
			{
				$("#11b").toggle();
				$("#11b1").toggle();
				$("#11b2").toggle();
				$("#11b3").toggle();
				$("#11b4").toggle();
				$("#11b5").toggle();
				$("#11b6").toggle();

			}
		if($("#11c").is(":visible"))
			{
				$("#11c").toggle();
				$("#11c1").toggle();
				$("#11c2").toggle();
			}
		if($("#12a").is(":visible"))
			{
				$("#12a").toggle();
			}
	}
	function closeOpenSession7a()
	{
		if($("#2a").is(":visible"))
			{
				$("#2a").toggle();
				$("#2a1").toggle();
				$("#2a2").toggle();
				$("#2a3").toggle();
				$("#2a4").toggle();
				$("#2a5").toggle();
				$("#2a6").toggle();
			}
		if($("#2b").is(":visible"))
			{
				$("#2b").toggle();
				$("#2b1").toggle();
				$("#2b2").toggle();
			}
		if($("#2c").is(":visible"))
			{
				$("#2c").toggle();
				$("#2c1").toggle();
				$("#2c2").toggle();
			}
		if($("#3a").is(":visible"))
			{
				$("#3a").toggle();
				$("#3a1").toggle();
				$("#3a2").toggle();
				$("#3a3").toggle();
				$("#3a4").toggle();
				$("#3a5").toggle();
				$("#3a6").toggle();
				$("#3a7").toggle();
			}
		if($("#3b").is(":visible"))
			{
				$("#3b").toggle();
				$("#3b1").toggle();
				$("#3b2").toggle();
			}
		if($("#3c").is(":visible"))
			{
				$("#3c").toggle();
				$("#3c1").toggle();
				$("#3c2").toggle();
			}
		if($("#6a").is(":visible"))
			{
				$("#6a").toggle();
				$("#6a1").toggle();
				$("#6a2").toggle();
				$("#6a3").toggle();
				$("#6a4").toggle();
				$("#6a5").toggle();
			}
		if($("#6b").is(":visible"))
			{
				$("#6b").toggle();
				$("#6b1").toggle();
				$("#6b2").toggle();
				$("#6b3").toggle();
			}
		if($("#6c").is(":visible"))
			{
				$("#6c").toggle();
				$("#6c1").toggle();
				$("#6c2").toggle();
				$("#6c3").toggle();
				$("#6c4").toggle();
			}
		if($("#7b").is(":visible"))
			{
				$("#7b").toggle();
				$("#7b1").toggle();
				$("#7b2").toggle();
				$("#7b3").toggle();
				$("#7b4").toggle();
				$("#7b5").toggle();
			}
		if($("#7c").is(":visible"))
			{
				$("#7c").toggle();
				$("#7c1").toggle();
				$("#7c2").toggle();
			}
		if($("#10a").is(":visible"))
			{
				$("#10a").toggle();
				$("#10a1").toggle();
				$("#10a2").toggle();
				$("#10a3").toggle();
			}
		if($("#10b").is(":visible"))
			{
				$("#10b").toggle();
				$("#10b1").toggle();
				$("#10b2").toggle();
				$("#10b3").toggle();
				$("#10b4").toggle();
				$("#10b5").toggle();
				$("#10b6").toggle();
			}
		if($("#10c").is(":visible"))
			{
				$("#10c").toggle();
				$("#10c1").toggle();
				$("#10c2").toggle();
			}
		if($("#11a").is(":visible"))
			{
				$("#11a").toggle();
				$("#11a1").toggle();
				$("#11a2").toggle();
				$("#11a3").toggle();
			}
		if($("#11b").is(":visible"))
			{
				$("#11b").toggle();
				$("#11b1").toggle();
				$("#11b2").toggle();
				$("#11b3").toggle();
				$("#11b4").toggle();
				$("#11b5").toggle();
				$("#11b6").toggle();

			}
		if($("#11c").is(":visible"))
			{
				$("#11c").toggle();
				$("#11c1").toggle();
				$("#11c2").toggle();
			}
		if($("#12a").is(":visible"))
			{
				$("#12a").toggle();
			}
	}
	function closeOpenSession7b()
	{
		if($("#2a").is(":visible"))
			{
				$("#2a").toggle();
				$("#2a1").toggle();
				$("#2a2").toggle();
				$("#2a3").toggle();
				$("#2a4").toggle();
				$("#2a5").toggle();
				$("#2a6").toggle();
			}
		if($("#2b").is(":visible"))
			{
				$("#2b").toggle();
				$("#2b1").toggle();
				$("#2b2").toggle();
			}
		if($("#2c").is(":visible"))
			{
				$("#2c").toggle();
				$("#2c1").toggle();
				$("#2c2").toggle();
			}
		if($("#3a").is(":visible"))
			{
				$("#3a").toggle();
				$("#3a1").toggle();
				$("#3a2").toggle();
				$("#3a3").toggle();
				$("#3a4").toggle();
				$("#3a5").toggle();
				$("#3a6").toggle();
				$("#3a7").toggle();
			}
		if($("#3b").is(":visible"))
			{
				$("#3b").toggle();
				$("#3b1").toggle();
				$("#3b2").toggle();
			}
		if($("#3c").is(":visible"))
			{
				$("#3c").toggle();
				$("#3c1").toggle();
				$("#3c2").toggle();
			}
		if($("#6a").is(":visible"))
			{
				$("#6a").toggle();
				$("#6a1").toggle();
				$("#6a2").toggle();
				$("#6a3").toggle();
				$("#6a4").toggle();
				$("#6a5").toggle();
			}
		if($("#6b").is(":visible"))
			{
				$("#6b").toggle();
				$("#6b1").toggle();
				$("#6b2").toggle();
				$("#6b3").toggle();
			}
		if($("#6c").is(":visible"))
			{
				$("#6c").toggle();
				$("#6c1").toggle();
				$("#6c2").toggle();
				$("#6c3").toggle();
				$("#6c4").toggle();
			}
		if($("#7a").is(":visible"))
			{
				$("#7a").toggle();
				$("#7a1").toggle();
				$("#7a2").toggle();
				$("#7a3").toggle();
				$("#7a4").toggle();
				$("#7a5").toggle();
				$("#7a6").toggle();
			}
		if($("#7c").is(":visible"))
			{
				$("#7c").toggle();
				$("#7c1").toggle();
				$("#7c2").toggle();
			}
		if($("#10a").is(":visible"))
			{
				$("#10a").toggle();
				$("#10a1").toggle();
				$("#10a2").toggle();
				$("#10a3").toggle();
			}
		if($("#10b").is(":visible"))
			{
				$("#10b").toggle();
				$("#10b1").toggle();
				$("#10b2").toggle();
				$("#10b3").toggle();
				$("#10b4").toggle();
				$("#10b5").toggle();
				$("#10b6").toggle();
			}
		if($("#10c").is(":visible"))
			{
				$("#10c").toggle();
				$("#10c1").toggle();
				$("#10c2").toggle();
			}
		if($("#11a").is(":visible"))
			{
				$("#11a").toggle();
				$("#11a1").toggle();
				$("#11a2").toggle();
				$("#11a3").toggle();
			}
		if($("#11b").is(":visible"))
			{
				$("#11b").toggle();
				$("#11b1").toggle();
				$("#11b2").toggle();
				$("#11b3").toggle();
				$("#11b4").toggle();
				$("#11b5").toggle();
				$("#11b6").toggle();

			}
		if($("#11c").is(":visible"))
			{
				$("#11c").toggle();
				$("#11c1").toggle();
				$("#11c2").toggle();
			}
		if($("#12a").is(":visible"))
			{
				$("#12a").toggle();
			}
	}
	function closeOpenSession7c()
	{
		if($("#2a").is(":visible"))
			{
				$("#2a").toggle();
				$("#2a1").toggle();
				$("#2a2").toggle();
				$("#2a3").toggle();
				$("#2a4").toggle();
				$("#2a5").toggle();
				$("#2a6").toggle();
			}
		if($("#2b").is(":visible"))
			{
				$("#2b").toggle();
				$("#2b1").toggle();
				$("#2b2").toggle();
			}
		if($("#2c").is(":visible"))
			{
				$("#2c").toggle();
				$("#2c1").toggle();
				$("#2c2").toggle();
			}
		if($("#3a").is(":visible"))
			{
				$("#3a").toggle();
				$("#3a1").toggle();
				$("#3a2").toggle();
				$("#3a3").toggle();
				$("#3a4").toggle();
				$("#3a5").toggle();
				$("#3a6").toggle();
				$("#3a7").toggle();
			}
		if($("#3b").is(":visible"))
			{
				$("#3b").toggle();
				$("#3b1").toggle();
				$("#3b2").toggle();
			}
		if($("#3c").is(":visible"))
			{
				$("#3c").toggle();
				$("#3c1").toggle();
				$("#3c2").toggle();
			}
		if($("#6a").is(":visible"))
			{
				$("#6a").toggle();
				$("#6a1").toggle();
				$("#6a2").toggle();
				$("#6a3").toggle();
				$("#6a4").toggle();
				$("#6a5").toggle();
			}
		if($("#6b").is(":visible"))
			{
				$("#6b").toggle();
				$("#6b1").toggle();
				$("#6b2").toggle();
				$("#6b3").toggle();
			}
		if($("#6c").is(":visible"))
			{
				$("#6c").toggle();
				$("#6c1").toggle();
				$("#6c2").toggle();
				$("#6c3").toggle();
				$("#6c4").toggle();
			}
		if($("#7a").is(":visible"))
			{
				$("#7a").toggle();
				$("#7a1").toggle();
				$("#7a2").toggle();
				$("#7a3").toggle();
				$("#7a4").toggle();
				$("#7a5").toggle();
				$("#7a6").toggle();
			}
		if($("#7b").is(":visible"))
			{
				$("#7b").toggle();
				$("#7b1").toggle();
				$("#7b2").toggle();
				$("#7b3").toggle();
				$("#7b4").toggle();
				$("#7b5").toggle();
			}
		if($("#10a").is(":visible"))
			{
				$("#10a").toggle();
				$("#10a1").toggle();
				$("#10a2").toggle();
				$("#10a3").toggle();
			}
		if($("#10b").is(":visible"))
			{
				$("#10b").toggle();
				$("#10b1").toggle();
				$("#10b2").toggle();
				$("#10b3").toggle();
				$("#10b4").toggle();
				$("#10b5").toggle();
				$("#10b6").toggle();
			}
		if($("#10c").is(":visible"))
			{
				$("#10c").toggle();
				$("#10c1").toggle();
				$("#10c2").toggle();
			}
		if($("#11a").is(":visible"))
			{
				$("#11a").toggle();
				$("#11a1").toggle();
				$("#11a2").toggle();
				$("#11a3").toggle();
			}
		if($("#11b").is(":visible"))
			{
				$("#11b").toggle();
				$("#11b1").toggle();
				$("#11b2").toggle();
				$("#11b3").toggle();
				$("#11b4").toggle();
				$("#11b5").toggle();
				$("#11b6").toggle();

			}
		if($("#11c").is(":visible"))
			{
				$("#11c").toggle();
				$("#11c1").toggle();
				$("#11c2").toggle();
			}
		if($("#12a").is(":visible"))
			{
				$("#12a").toggle();
			}
	}
	function closeOpenSession10a()
	{
		if($("#2a").is(":visible"))
			{
				$("#2a").toggle();
				$("#2a1").toggle();
				$("#2a2").toggle();
				$("#2a3").toggle();
				$("#2a4").toggle();
				$("#2a5").toggle();
				$("#2a6").toggle();
			}
		if($("#2b").is(":visible"))
			{
				$("#2b").toggle();
				$("#2b1").toggle();
				$("#2b2").toggle();
			}
		if($("#2c").is(":visible"))
			{
				$("#2c").toggle();
				$("#2c1").toggle();
				$("#2c2").toggle();
			}
		if($("#3a").is(":visible"))
			{
				$("#3a").toggle();
				$("#3a1").toggle();
				$("#3a2").toggle();
				$("#3a3").toggle();
				$("#3a4").toggle();
				$("#3a5").toggle();
				$("#3a6").toggle();
				$("#3a7").toggle();
			}
		if($("#3b").is(":visible"))
			{
				$("#3b").toggle();
				$("#3b1").toggle();
				$("#3b2").toggle();
			}
		if($("#3c").is(":visible"))
			{
				$("#3c").toggle();
				$("#3c1").toggle();
				$("#3c2").toggle();
			}
		if($("#6a").is(":visible"))
			{
				$("#6a").toggle();
				$("#6a1").toggle();
				$("#6a2").toggle();
				$("#6a3").toggle();
				$("#6a4").toggle();
				$("#6a5").toggle();
			}
		if($("#6b").is(":visible"))
			{
				$("#6b").toggle();
				$("#6b1").toggle();
				$("#6b2").toggle();
				$("#6b3").toggle();
			}
		if($("#6c").is(":visible"))
			{
				$("#6c").toggle();
				$("#6c1").toggle();
				$("#6c2").toggle();
				$("#6c3").toggle();
				$("#6c4").toggle();
			}
		if($("#7a").is(":visible"))
			{
				$("#7a").toggle();
				$("#7a1").toggle();
				$("#7a2").toggle();
				$("#7a3").toggle();
				$("#7a4").toggle();
				$("#7a5").toggle();
				$("#7a6").toggle();
			}
		if($("#7b").is(":visible"))
			{
				$("#7b").toggle();
				$("#7b1").toggle();
				$("#7b2").toggle();
				$("#7b3").toggle();
				$("#7b4").toggle();
				$("#7b5").toggle();
			}
		if($("#7c").is(":visible"))
			{
				$("#7c").toggle();
				$("#7c1").toggle();
				$("#7c2").toggle();
			}
		if($("#10b").is(":visible"))
			{
				$("#10b").toggle();
				$("#10b1").toggle();
				$("#10b2").toggle();
				$("#10b3").toggle();
				$("#10b4").toggle();
				$("#10b5").toggle();
				$("#10b6").toggle();
			}
		if($("#10c").is(":visible"))
			{
				$("#10c").toggle();
				$("#10c1").toggle();
				$("#10c2").toggle();
			}
		if($("#11a").is(":visible"))
			{
				$("#11a").toggle();
				$("#11a1").toggle();
				$("#11a2").toggle();
				$("#11a3").toggle();
			}
		if($("#11b").is(":visible"))
			{
				$("#11b").toggle();
				$("#11b1").toggle();
				$("#11b2").toggle();
				$("#11b3").toggle();
				$("#11b4").toggle();
				$("#11b5").toggle();
				$("#11b6").toggle();

			}
		if($("#11c").is(":visible"))
			{
				$("#11c").toggle();
				$("#11c1").toggle();
				$("#11c2").toggle();
			}
		if($("#12a").is(":visible"))
			{
				$("#12a").toggle();
			}
	}
	function closeOpenSession10b()
	{
		if($("#2a").is(":visible"))
			{
				$("#2a").toggle();
				$("#2a1").toggle();
				$("#2a2").toggle();
				$("#2a3").toggle();
				$("#2a4").toggle();
				$("#2a5").toggle();
				$("#2a6").toggle();
			}
		if($("#2b").is(":visible"))
			{
				$("#2b").toggle();
				$("#2b1").toggle();
				$("#2b2").toggle();
			}
		if($("#2c").is(":visible"))
			{
				$("#2c").toggle();
				$("#2c1").toggle();
				$("#2c2").toggle();
			}
		if($("#3a").is(":visible"))
			{
				$("#3a").toggle();
				$("#3a1").toggle();
				$("#3a2").toggle();
				$("#3a3").toggle();
				$("#3a4").toggle();
				$("#3a5").toggle();
				$("#3a6").toggle();
				$("#3a7").toggle();
			}
		if($("#3b").is(":visible"))
			{
				$("#3b").toggle();
				$("#3b1").toggle();
				$("#3b2").toggle();
			}
		if($("#3c").is(":visible"))
			{
				$("#3c").toggle();
				$("#3c1").toggle();
				$("#3c2").toggle();
			}
		if($("#6a").is(":visible"))
			{
				$("#6a").toggle();
				$("#6a1").toggle();
				$("#6a2").toggle();
				$("#6a3").toggle();
				$("#6a4").toggle();
				$("#6a5").toggle();
			}
		if($("#6b").is(":visible"))
			{
				$("#6b").toggle();
				$("#6b1").toggle();
				$("#6b2").toggle();
				$("#6b3").toggle();
			}
		if($("#6c").is(":visible"))
			{
				$("#6c").toggle();
				$("#6c1").toggle();
				$("#6c2").toggle();
				$("#6c3").toggle();
				$("#6c4").toggle();
			}
		if($("#7a").is(":visible"))
			{
				$("#7a").toggle();
				$("#7a1").toggle();
				$("#7a2").toggle();
				$("#7a3").toggle();
				$("#7a4").toggle();
				$("#7a5").toggle();
				$("#7a6").toggle();
			}
		if($("#7b").is(":visible"))
			{
				$("#7b").toggle();
				$("#7b1").toggle();
				$("#7b2").toggle();
				$("#7b3").toggle();
				$("#7b4").toggle();
				$("#7b5").toggle();
			}
		if($("#7c").is(":visible"))
			{
				$("#7c").toggle();
				$("#7c1").toggle();
				$("#7c2").toggle();
			}
		if($("#10a").is(":visible"))
			{
				$("#10a").toggle();
				$("#10a1").toggle();
				$("#10a2").toggle();
				$("#10a3").toggle();
			}
		if($("#10c").is(":visible"))
			{
				$("#10c").toggle();
				$("#10c1").toggle();
				$("#10c2").toggle();
			}
		if($("#11a").is(":visible"))
			{
				$("#11a").toggle();
				$("#11a1").toggle();
				$("#11a2").toggle();
				$("#11a3").toggle();
			}
		if($("#11b").is(":visible"))
			{
				$("#11b").toggle();
				$("#11b1").toggle();
				$("#11b2").toggle();
				$("#11b3").toggle();
				$("#11b4").toggle();
				$("#11b5").toggle();
				$("#11b6").toggle();

			}
		if($("#11c").is(":visible"))
			{
				$("#11c").toggle();
				$("#11c1").toggle();
				$("#11c2").toggle();
			}
		if($("#12a").is(":visible"))
			{
				$("#12a").toggle();
			}
	}
	
	function closeOpenSession10c()
	{
		if($("#2a").is(":visible"))
			{
				$("#2a").toggle();
				$("#2a1").toggle();
				$("#2a2").toggle();
				$("#2a3").toggle();
				$("#2a4").toggle();
				$("#2a5").toggle();
				$("#2a6").toggle();
			}
		if($("#2b").is(":visible"))
			{
				$("#2b").toggle();
				$("#2b1").toggle();
				$("#2b2").toggle();
			}
		if($("#2c").is(":visible"))
			{
				$("#2c").toggle();
				$("#2c1").toggle();
				$("#2c2").toggle();
			}
		if($("#3a").is(":visible"))
			{
				$("#3a").toggle();
				$("#3a1").toggle();
				$("#3a2").toggle();
				$("#3a3").toggle();
				$("#3a4").toggle();
				$("#3a5").toggle();
				$("#3a6").toggle();
				$("#3a7").toggle();
			}
		if($("#3b").is(":visible"))
			{
				$("#3b").toggle();
				$("#3b1").toggle();
				$("#3b2").toggle();
			}
		if($("#3c").is(":visible"))
			{
				$("#3c").toggle();
				$("#3c1").toggle();
				$("#3c2").toggle();
			}
		if($("#6a").is(":visible"))
			{
				$("#6a").toggle();
				$("#6a1").toggle();
				$("#6a2").toggle();
				$("#6a3").toggle();
				$("#6a4").toggle();
				$("#6a5").toggle();
			}
		if($("#6b").is(":visible"))
			{
				$("#6b").toggle();
				$("#6b1").toggle();
				$("#6b2").toggle();
				$("#6b3").toggle();
			}
		if($("#6c").is(":visible"))
			{
				$("#6c").toggle();
				$("#6c1").toggle();
				$("#6c2").toggle();
				$("#6c3").toggle();
				$("#6c4").toggle();
			}
		if($("#7a").is(":visible"))
			{
				$("#7a").toggle();
				$("#7a1").toggle();
				$("#7a2").toggle();
				$("#7a3").toggle();
				$("#7a4").toggle();
				$("#7a5").toggle();
				$("#7a6").toggle();
			}
		if($("#7b").is(":visible"))
			{
				$("#7b").toggle();
				$("#7b1").toggle();
				$("#7b2").toggle();
				$("#7b3").toggle();
				$("#7b4").toggle();
				$("#7b5").toggle();
			}
		if($("#7c").is(":visible"))
			{
				$("#7c").toggle();
				$("#7c1").toggle();
				$("#7c2").toggle();
			}
		if($("#10a").is(":visible"))
			{
				$("#10a").toggle();
				$("#10a1").toggle();
				$("#10a2").toggle();
				$("#10a3").toggle();
			}
		if($("#10b").is(":visible"))
			{
				$("#10b").toggle();
				$("#10b1").toggle();
				$("#10b2").toggle();
				$("#10b3").toggle();
				$("#10b4").toggle();
				$("#10b5").toggle();
				$("#10b6").toggle();
			}
		if($("#11a").is(":visible"))
			{
				$("#11a").toggle();
				$("#11a1").toggle();
				$("#11a2").toggle();
				$("#11a3").toggle();
			}
		if($("#11b").is(":visible"))
			{
				$("#11b").toggle();
				$("#11b1").toggle();
				$("#11b2").toggle();
				$("#11b3").toggle();
				$("#11b4").toggle();
				$("#11b5").toggle();
				$("#11b6").toggle();

			}
		if($("#11c").is(":visible"))
			{
				$("#11c").toggle();
				$("#11c1").toggle();
				$("#11c2").toggle();
			}
		if($("#12a").is(":visible"))
			{
				$("#12a").toggle();
			}
	}
	function closeOpenSession11a()
	{
		if($("#2a").is(":visible"))
			{
				$("#2a").toggle();
				$("#2a1").toggle();
				$("#2a2").toggle();
				$("#2a3").toggle();
				$("#2a4").toggle();
				$("#2a5").toggle();
				$("#2a6").toggle();
			}
		if($("#2b").is(":visible"))
			{
				$("#2b").toggle();
				$("#2b1").toggle();
				$("#2b2").toggle();
			}
		if($("#2c").is(":visible"))
			{
				$("#2c").toggle();
				$("#2c1").toggle();
				$("#2c2").toggle();
			}
		if($("#3a").is(":visible"))
			{
				$("#3a").toggle();
				$("#3a1").toggle();
				$("#3a2").toggle();
				$("#3a3").toggle();
				$("#3a4").toggle();
				$("#3a5").toggle();
				$("#3a6").toggle();
				$("#3a7").toggle();
			}
		if($("#3b").is(":visible"))
			{
				$("#3b").toggle();
				$("#3b1").toggle();
				$("#3b2").toggle();
			}
		if($("#3c").is(":visible"))
			{
				$("#3c").toggle();
				$("#3c1").toggle();
				$("#3c2").toggle();
			}
		if($("#6a").is(":visible"))
			{
				$("#6a").toggle();
				$("#6a1").toggle();
				$("#6a2").toggle();
				$("#6a3").toggle();
				$("#6a4").toggle();
				$("#6a5").toggle();
			}
		if($("#6b").is(":visible"))
			{
				$("#6b").toggle();
				$("#6b1").toggle();
				$("#6b2").toggle();
				$("#6b3").toggle();
			}
		if($("#6c").is(":visible"))
			{
				$("#6c").toggle();
				$("#6c1").toggle();
				$("#6c2").toggle();
				$("#6c3").toggle();
				$("#6c4").toggle();
			}
		if($("#7a").is(":visible"))
			{
				$("#7a").toggle();
				$("#7a1").toggle();
				$("#7a2").toggle();
				$("#7a3").toggle();
				$("#7a4").toggle();
				$("#7a5").toggle();
				$("#7a6").toggle();
			}
		if($("#7b").is(":visible"))
			{
				$("#7b").toggle();
				$("#7b1").toggle();
				$("#7b2").toggle();
				$("#7b3").toggle();
				$("#7b4").toggle();
				$("#7b5").toggle();
			}
		if($("#7c").is(":visible"))
			{
				$("#7c").toggle();
				$("#7c1").toggle();
				$("#7c2").toggle();
			}
		if($("#10a").is(":visible"))
			{
				$("#10a").toggle();
				$("#10a1").toggle();
				$("#10a2").toggle();
				$("#10a3").toggle();
			}
		if($("#10b").is(":visible"))
			{
				$("#10b").toggle();
				$("#10b1").toggle();
				$("#10b2").toggle();
				$("#10b3").toggle();
				$("#10b4").toggle();
				$("#10b5").toggle();
				$("#10b6").toggle();
			}
		if($("#10c").is(":visible"))
			{
				$("#10c").toggle();
				$("#10c1").toggle();
				$("#10c2").toggle();
			}
		if($("#11b").is(":visible"))
			{
				$("#11b").toggle();
				$("#11b1").toggle();
				$("#11b2").toggle();
				$("#11b3").toggle();
				$("#11b4").toggle();
				$("#11b5").toggle();
				$("#11b6").toggle();

			}
		if($("#11c").is(":visible"))
			{
				$("#11c").toggle();
				$("#11c1").toggle();
				$("#11c2").toggle();
			}
		if($("#12a").is(":visible"))
			{
				$("#12a").toggle();
			}
	}
	function closeOpenSession11b()
	{
		if($("#2a").is(":visible"))
			{
				$("#2a").toggle();
				$("#2a1").toggle();
				$("#2a2").toggle();
				$("#2a3").toggle();
				$("#2a4").toggle();
				$("#2a5").toggle();
				$("#2a6").toggle();
			}
		if($("#2b").is(":visible"))
			{
				$("#2b").toggle();
				$("#2b1").toggle();
				$("#2b2").toggle();
			}
		if($("#2c").is(":visible"))
			{
				$("#2c").toggle();
				$("#2c1").toggle();
				$("#2c2").toggle();
			}
		if($("#3a").is(":visible"))
			{
				$("#3a").toggle();
				$("#3a1").toggle();
				$("#3a2").toggle();
				$("#3a3").toggle();
				$("#3a4").toggle();
				$("#3a5").toggle();
				$("#3a6").toggle();
				$("#3a7").toggle();
			}
		if($("#3b").is(":visible"))
			{
				$("#3b").toggle();
				$("#3b1").toggle();
				$("#3b2").toggle();
			}
		if($("#3c").is(":visible"))
			{
				$("#3c").toggle();
				$("#3c1").toggle();
				$("#3c2").toggle();
			}
		if($("#6a").is(":visible"))
			{
				$("#6a").toggle();
				$("#6a1").toggle();
				$("#6a2").toggle();
				$("#6a3").toggle();
				$("#6a4").toggle();
				$("#6a5").toggle();
			}
		if($("#6b").is(":visible"))
			{
				$("#6b").toggle();
				$("#6b1").toggle();
				$("#6b2").toggle();
				$("#6b3").toggle();
			}
		if($("#6c").is(":visible"))
			{
				$("#6c").toggle();
				$("#6c1").toggle();
				$("#6c2").toggle();
				$("#6c3").toggle();
				$("#6c4").toggle();
			}
		if($("#7a").is(":visible"))
			{
				$("#7a").toggle();
				$("#7a1").toggle();
				$("#7a2").toggle();
				$("#7a3").toggle();
				$("#7a4").toggle();
				$("#7a5").toggle();
				$("#7a6").toggle();
			}
		if($("#7b").is(":visible"))
			{
				$("#7b").toggle();
				$("#7b1").toggle();
				$("#7b2").toggle();
				$("#7b3").toggle();
				$("#7b4").toggle();
				$("#7b5").toggle();
			}
		if($("#7c").is(":visible"))
			{
				$("#7c").toggle();
				$("#7c1").toggle();
				$("#7c2").toggle();
			}
		if($("#10a").is(":visible"))
			{
				$("#10a").toggle();
				$("#10a1").toggle();
				$("#10a2").toggle();
				$("#10a3").toggle();
			}
		if($("#10b").is(":visible"))
			{
				$("#10b").toggle();
				$("#10b1").toggle();
				$("#10b2").toggle();
				$("#10b3").toggle();
				$("#10b4").toggle();
				$("#10b5").toggle();
				$("#10b6").toggle();
			}
		if($("#10c").is(":visible"))
			{
				$("#10c").toggle();
				$("#10c1").toggle();
				$("#10c2").toggle();
			}
		if($("#11a").is(":visible"))
			{
				$("#11a").toggle();
				$("#11a1").toggle();
				$("#11a2").toggle();
				$("#11a3").toggle();
			}
		if($("#11c").is(":visible"))
			{
				$("#11c").toggle();
				$("#11c1").toggle();
				$("#11c2").toggle();
			}
		if($("#12a").is(":visible"))
			{
				$("#12a").toggle();
			}
	}
	function closeOpenSession11c()
	{
		if($("#2a").is(":visible"))
			{
				$("#2a").toggle();
				$("#2a1").toggle();
				$("#2a2").toggle();
				$("#2a3").toggle();
				$("#2a4").toggle();
				$("#2a5").toggle();
				$("#2a6").toggle();
			}
		if($("#2b").is(":visible"))
			{
				$("#2b").toggle();
				$("#2b1").toggle();
				$("#2b2").toggle();
			}
		if($("#2c").is(":visible"))
			{
				$("#2c").toggle();
				$("#2c1").toggle();
				$("#2c2").toggle();
			}
		if($("#3a").is(":visible"))
			{
				$("#3a").toggle();
				$("#3a1").toggle();
				$("#3a2").toggle();
				$("#3a3").toggle();
				$("#3a4").toggle();
				$("#3a5").toggle();
				$("#3a6").toggle();
				$("#3a7").toggle();
			}
		if($("#3b").is(":visible"))
			{
				$("#3b").toggle();
				$("#3b1").toggle();
				$("#3b2").toggle();
			}
		if($("#3c").is(":visible"))
			{
				$("#3c").toggle();
				$("#3c1").toggle();
				$("#3c2").toggle();
			}
		if($("#6a").is(":visible"))
			{
				$("#6a").toggle();
				$("#6a1").toggle();
				$("#6a2").toggle();
				$("#6a3").toggle();
				$("#6a4").toggle();
				$("#6a5").toggle();
			}
		if($("#6b").is(":visible"))
			{
				$("#6b").toggle();
				$("#6b1").toggle();
				$("#6b2").toggle();
				$("#6b3").toggle();
			}
		if($("#6c").is(":visible"))
			{
				$("#6c").toggle();
				$("#6c1").toggle();
				$("#6c2").toggle();
				$("#6c3").toggle();
				$("#6c4").toggle();
			}
		if($("#7a").is(":visible"))
			{
				$("#7a").toggle();
				$("#7a1").toggle();
				$("#7a2").toggle();
				$("#7a3").toggle();
				$("#7a4").toggle();
				$("#7a5").toggle();
				$("#7a6").toggle();
			}
		if($("#7b").is(":visible"))
			{
				$("#7b").toggle();
				$("#7b1").toggle();
				$("#7b2").toggle();
				$("#7b3").toggle();
				$("#7b4").toggle();
				$("#7b5").toggle();
			}
		if($("#7c").is(":visible"))
			{
				$("#7c").toggle();
				$("#7c1").toggle();
				$("#7c2").toggle();
			}
		if($("#10a").is(":visible"))
			{
				$("#10a").toggle();
				$("#10a1").toggle();
				$("#10a2").toggle();
				$("#10a3").toggle();
			}
		if($("#10b").is(":visible"))
			{
				$("#10b").toggle();
				$("#10b1").toggle();
				$("#10b2").toggle();
				$("#10b3").toggle();
				$("#10b4").toggle();
				$("#10b5").toggle();
				$("#10b6").toggle();
			}
		if($("#10c").is(":visible"))
			{
				$("#10c").toggle();
				$("#10c1").toggle();
				$("#10c2").toggle();
			}
		if($("#11a").is(":visible"))
			{
				$("#11a").toggle();
				$("#11a1").toggle();
				$("#11a2").toggle();
				$("#11a3").toggle();
			}
		if($("#11b").is(":visible"))
			{
				$("#11b").toggle();
				$("#11b1").toggle();
				$("#11b2").toggle();
				$("#11b3").toggle();
				$("#11b4").toggle();
				$("#11b5").toggle();
				$("#11b6").toggle();

			}
		if($("#12a").is(":visible"))
			{
				$("#12a").toggle();
			}
	}
	
	function closeOpenSession12a()
	{
		if($("#2a").is(":visible"))
			{
				$("#2a").toggle();
				$("#2a1").toggle();
				$("#2a2").toggle();
				$("#2a3").toggle();
				$("#2a4").toggle();
				$("#2a5").toggle();
				$("#2a6").toggle();
			}
		if($("#2b").is(":visible"))
			{
				$("#2b").toggle();
				$("#2b1").toggle();
				$("#2b2").toggle();
			}
		if($("#2c").is(":visible"))
			{
				$("#2c").toggle();
				$("#2c1").toggle();
				$("#2c2").toggle();
			}
		if($("#3a").is(":visible"))
			{
				$("#3a").toggle();
				$("#3a1").toggle();
				$("#3a2").toggle();
				$("#3a3").toggle();
				$("#3a4").toggle();
				$("#3a5").toggle();
				$("#3a6").toggle();
				$("#3a7").toggle();
			}
		if($("#3b").is(":visible"))
			{
				$("#3b").toggle();
				$("#3b1").toggle();
				$("#3b2").toggle();
			}
		if($("#3c").is(":visible"))
			{
				$("#3c").toggle();
				$("#3c1").toggle();
				$("#3c2").toggle();
			}
		if($("#6a").is(":visible"))
			{
				$("#6a").toggle();
				$("#6a1").toggle();
				$("#6a2").toggle();
				$("#6a3").toggle();
				$("#6a4").toggle();
				$("#6a5").toggle();
			}
		if($("#6b").is(":visible"))
			{
				$("#6b").toggle();
				$("#6b1").toggle();
				$("#6b2").toggle();
				$("#6b3").toggle();
			}
		if($("#6c").is(":visible"))
			{
				$("#6c").toggle();
				$("#6c1").toggle();
				$("#6c2").toggle();
				$("#6c3").toggle();
				$("#6c4").toggle();
			}
		if($("#7a").is(":visible"))
			{
				$("#7a").toggle();
				$("#7a1").toggle();
				$("#7a2").toggle();
				$("#7a3").toggle();
				$("#7a4").toggle();
				$("#7a5").toggle();
				$("#7a6").toggle();
			}
		if($("#7b").is(":visible"))
			{
				$("#7b").toggle();
				$("#7b1").toggle();
				$("#7b2").toggle();
				$("#7b3").toggle();
				$("#7b4").toggle();
				$("#7b5").toggle();
			}
		if($("#7c").is(":visible"))
			{
				$("#7c").toggle();
				$("#7c1").toggle();
				$("#7c2").toggle();
			}
		if($("#10a").is(":visible"))
			{
				$("#10a").toggle();
				$("#10a1").toggle();
				$("#10a2").toggle();
				$("#10a3").toggle();
			}
		if($("#10b").is(":visible"))
			{
				$("#10b").toggle();
				$("#10b1").toggle();
				$("#10b2").toggle();
				$("#10b3").toggle();
				$("#10b4").toggle();
				$("#10b5").toggle();
				$("#10b6").toggle();
			}
		if($("#10c").is(":visible"))
			{
				$("#10c").toggle();
				$("#10c1").toggle();
				$("#10c2").toggle();
				
			}
		if($("#11a").is(":visible"))
			{
				$("#11a").toggle();
				$("#11a1").toggle();
				$("#11a2").toggle();
				$("#11a3").toggle();
			}
		if($("#11b").is(":visible"))
			{
				$("#11b").toggle();
				$("#11b1").toggle();
				$("#11b2").toggle();
				$("#11b3").toggle();
				$("#11b4").toggle();
				$("#11b5").toggle();
				$("#11b6").toggle();
			}
		if($("#11c").is(":visible"))
			{
				$("#11c").toggle();
				$("#11c1").toggle();
				$("#11c2").toggle();
			}
	}
	
	$(document).ready(function(){
		$(".session2a").click(function(){
			closeOpenSession2a();
			$("#2a").toggle();
			$("#2a1").toggle();
			$("#2a2").toggle();
			$("#2a3").toggle();
			$("#2a4").toggle();
			$("#2a5").toggle();
			$("#2a6").toggle();
		});
		$(".session2b").click(function(){
			closeOpenSession2b();
			$("#2b").toggle();
			$("#2b1").toggle();
			$("#2b2").toggle();
		});
		$(".session2c").click(function(){
			closeOpenSession2c();
			$("#2c").toggle();
			$("#2c1").toggle();
			$("#2c2").toggle();
		});
		$(".session3a").click(function(){
			closeOpenSession3a();
			$("#3a").toggle();
			$("#3a1").toggle();
			$("#3a2").toggle();
			$("#3a3").toggle();
			$("#3a4").toggle();
			$("#3a5").toggle();
			$("#3a6").toggle();
			$("#3a7").toggle();
		});
		$(".session3b").click(function(){
			closeOpenSession3b();
			$("#3b").toggle();
			$("#3b1").toggle();
			$("#3b2").toggle();
		});
		$(".session3c").click(function(){
			closeOpenSession3c();
			$("#3c").toggle();
			$("#3c1").toggle();
			$("#3c2").toggle();
		});
		$(".session6a").click(function(){
			closeOpenSession6a();
			$("#6a").toggle();
			$("#6a1").toggle();
			$("#6a2").toggle();
			$("#6a3").toggle();
			$("#6a4").toggle();
			$("#6a5").toggle();
		});
		$(".session6b").click(function(){
			closeOpenSession6b();
			$("#6b").toggle();
			$("#6b1").toggle();
			$("#6b2").toggle();
			$("#6b3").toggle();
		});
		$(".session6c").click(function(){
			closeOpenSession6c();
			$("#6c").toggle();
			$("#6c1").toggle();
			$("#6c2").toggle();
			$("#6c3").toggle();
				$("#6c4").toggle();
		});
		$(".session7a").click(function(){
			closeOpenSession7a();
			$("#7a").toggle();
			$("#7a1").toggle();
			$("#7a2").toggle();
			$("#7a3").toggle();
			$("#7a4").toggle();
			$("#7a5").toggle();
			$("#7a6").toggle();
		});
		$(".session7b").click(function(){
			closeOpenSession7b();
			$("#7b").toggle();
			$("#7b1").toggle();
			$("#7b2").toggle();
			$("#7b3").toggle();
			$("#7b4").toggle();
			$("#7b5").toggle();
		});
		$(".session7c").click(function(){
			closeOpenSession7c();
			$("#7c").toggle();
			$("#7c1").toggle();
			$("#7c2").toggle();
		});
		$(".session10a").click(function(){
			closeOpenSession10a();
			$("#10a").toggle();
			$("#10a1").toggle();
			$("#10a2").toggle();
			$("#10a3").toggle();
		});
		$(".session10b").click(function(){
			closeOpenSession10b();
			$("#10b").toggle();
			$("#10b1").toggle();
			$("#10b2").toggle();
			$("#10b3").toggle();
			$("#10b4").toggle();
			$("#10b5").toggle();
			$("#10b6").toggle();
		});
		$(".session10c").click(function(){
			closeOpenSession10c();
			$("#10c").toggle();
			$("#10c1").toggle();
			$("#10c2").toggle();
			$("#10c3").toggle();
		});
		$(".session11a").click(function(){
			closeOpenSession11a();
			$("#11a").toggle();
			$("#11a1").toggle();
			$("#11a2").toggle();
			$("#11a3").toggle();
		});
		$(".session11b").click(function(){
			closeOpenSession11b();
			$("#11b").toggle();
			$("#11b1").toggle();
			$("#11b2").toggle();
			$("#11b3").toggle();
			$("#11b4").toggle();
			$("#11b5").toggle();
			$("#11b6").toggle();

		});
		$(".session11c").click(function(){
			closeOpenSession11c();
			$("#11c").toggle();
			$("#11c1").toggle();
			$("#11c2").toggle();
		});
		$(".session12a"). click(function(){
			closeOpenSession12a();
			$("#12a").toggle();
		});
	});
	</script>
    
</head>
<body data-spy="scroll" data-target="#site-nav">

<div id="wrap" class="wrap">
<header id="site-header" class="site-header valign-center"> 
        
        <div id="intro" class="intro">
		<!-- logo -->
                
            <img src="assets/images/logo_big.png" alt="Logo" longdesc="The empower logo consists of the the text EMPOWER 2018. Empower is written in mustard color text and 2018 in white color. The O of Empower is divided into four quadrants with each quadrant representing visual, hearing, physical and cognitive disablity respectively through universal icons." style=" width: 100%; height: auto; max-width: 594px;">
           
            
            <h1 style="color:#fff;">ASSISTIVE TECHNOLOGY CONFERENCE</h1>
			
            <h2>25 - 27 October 2018</h2>
            <a class="btn btn-white" data-scroll href="register">Register Now</a>
			<br><br>
            <a href="index.php#about" class="downArrow" data-scroll> <i class="fa fa-angle-down"></i></a>
        
        </div>
    </header>

<nav id="site-nav" class="navbar navbar-custom" data-spy="affix" data-offset-top="500">
		<div class="container">
			<!-- Brand and toggle get grouped for better mobile display -->
			<div class="navbar-header">
            
            	<!-- logo -->
                <div class="site-branding">
                    <a class="logo" href="index.php">
                        
                        <!-- logo image  -->
                        <img src="assets/images/logo.png" alt="Logo" longdesc="The empower logo consists of the the text EMPOWER 2018. Empower is written in mustard color text and 2018 in white color. The O of Empower is divided into four quadrants with each quadrant representing visual, hearing, physical and cognitive disablity respectively through universal icons." style=" width: 100%; height: auto; max-width: 275px;
                         margin-top: 5px;">
                    </a>
                </div>
            
            
				<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse-1">
					<span class="sr-only">Toggle navigation</span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
				
			</div>

			<!-- Collect the nav links, forms, and other content for toggling -->
			<div class="collapse navbar-collapse" id="navbar-collapse-1">
				<ul class="nav navbar-nav navbar-right">
					<!--<li><a href="index.php">Home</a></li>-->
                    <li><a href="index.php#about">Home</a></li>
					
					<li class="dropdown"><a href="#" class="dropdown-toggle" data-toggle="dropdown" >Program
                    <span class="caret"></span></a>
					<ul class="dropdown-menu">
	                        
							<li><a href="index.php#speakers">Speakers</a></li>
							<li><a href="index.php#program">Program Overview</a></li>
                            
							
						</ul>
					
					</li>
                    <li class="dropdown"><a class="dropdown-toggle" data-toggle="dropdown" href="#">Attend<span class="caret"></span></a>
						<ul class="dropdown-menu">
	                        <li><a href="index.php#registration">Register</a></li>
							<li><a href="index.php#accomodation">Accomodation</a></li>
                            
							
						</ul>
					
					</li>
					
					
					
					<li><a href="index.php#participate">Submit</a></li>
					<li><a href="index.php#exhibit">Exhibit</a></li>
					<li><a href="index.php#sponsorship">Sponsor</a></li>
					
					
					
					
                    <!--<li class="dropdown"><a class="dropdown-toggle" data-toggle="dropdown" href="#">Program<span class="caret"></span></a>
						<ul class="dropdown-menu">
	                        <li><a href="index.php#program">Program Overview</a></li>
							<li><a href="index.php#speakers">Key Note Speakers</a></li>
                            
							
						</ul>
					</li>-->
					<li><a href="committee.php">Committee</a>
						
					</li>
					
					
					
				 
					<!--<li><a href="index.php#sponsorship">Sponsors</a></li>-->
					
					 
				</ul>
				 
			</div><!-- /.navbar-collapse -->
		</div><!-- /.container -->
	</nav><!-- /.navbar -->
